// src/components/InputKeySetting.vue
<template>
  <form @submit="onSubmit">
    <div>
      <label>
        <p class="label">Key</p>
        <input 
          :value="keyString" 
          type="text" 
          required 
          class="input" 
          @keydown="onKeyDown" >
      </label>
    </div>
    <div>
      <label>
        <p class="label">Action</p>
        <select 
          :value="actionType" 
          type="select" 
          required 
          class="input" 
          @change="onChangeActionType">
          <option 
            disabled 
            value="">Please select one</option>
          <option v-for="(action, key) in actions">
            {{ key }}
          </option>
        </select>
      </label>
    </div>
    <div v-if="actions[actionType] && actions[actionType].hasValue">
      <label>
        <p class="label">Value</p>
        <input 
          :value="value" 
          type="text" 
          required 
          class="input" 
          @change="onChange" ><br>
        <p class="annotation">${title} and ${url} variables are available.</p>
      </label>
    </div>
    <div>
      <input 
        type="submit" 
        value="Add" 
        class="submit" >
    </div>
  </form>
</template>

<script>
import { detectKeyString } from 'key-string'
import actions from '../content/actions/index'

export default {
  name: 'InputKeySetting',
  data() {
    return {
      keyString: '',
      actionType: '',
      value: '',
      actions
    }
  },
  methods: {
    onSubmit(e) {
      e.preventDefault()
      this.$emit('on-submit', this.keyString, this.actionType, this.value)
    },

    onKeyDown(e) {
      const keyString = detectKeyString(e)
      if (!keyString.includes('Unknown')) {
        this.keyString = keyString
      }
    },

    onChangeActionType(e) {
      this.actionType = e.target.value
    },

    onChange(e) {
      this.value = e.target.value
    }
  }
}
</script>

<style lang="scss" scoped>
form {
  margin-top: 30px;
  padding: 20px 0;
  background-color: #fff;
}
div {
  width: 798px;
  margin: 0 auto;
}
.input {
  height: 20px;
  width: 100%;
  font-size: 1rem;
}
.submit {
  margin-top: 20px;
  padding: 5px 20px;
  border: 2px solid #6d9ee1;
  border-radius: 5px;
  background-color: #6d9ee1;
  color: #fff;
}
.label {
  font-size: 1rem;
  margin: 25px 0 10px;
}
.annotation {
  color: #888;
}
</style>

// src/components/InputKeySetting.tsx
import { useState } from "react";
import detectKeyString from "../content/detectKeyString";
import { actions } from "../content/actions";

interface Props {
  addHotKey: (hotKey: string, actionType: string, actionValue: string) => void;
}

const ActionTypeHavingValue = "CopyToClipboard";

export function InputKeySetting({ addHotKey }: Props) {
  const [hotKey, setHotKey] = useState("");
  // FIXME: initial value from `actions`
  const [actionType, setActionType] = useState("CopyToClipboard");
  const [actionValue, setActionValue] = useState("");

  // FIXME: properly validate and control visibility
  const hasActionValue = actionType === ActionTypeHavingValue;

  const updateHotKey: React.KeyboardEventHandler = (e) => {
    e.preventDefault();
    // FIXME: valid type
    const keyString = detectKeyString(e as unknown as KeyboardEvent);
    setHotKey(keyString);
  };

  const updateActionType: React.ChangeEventHandler<HTMLSelectElement> = (e) => {
    const newActionType = e.target.value;
    setActionType(newActionType);

    // clear unused actionValue
    if (newActionType !== ActionTypeHavingValue) {
      setActionValue("");
    }
  };

  return (
    <form className="grid grid-cols-[100px_1fr] items-center gap-y-6">
      <label htmlFor="hot-key" className="text-sm text-gray-500">
        Hot Key
      </label>
      {/* Add `onChange` to avoid controlled components warning */}
      <input
        id="hot-key"
        className="border-b-2 text-lg text-black"
        type="text"
        value={hotKey}
        onChange={() => {}}
        onKeyDown={updateHotKey}
      />

      <label htmlFor="action-type" className="text-sm text-gray-500">
        Action
      </label>
      <select id="action-type" className="text-lg" onChange={updateActionType}>
        {Object.keys(actions).map((actionType) => (
          <option key={actionType}>{actionType}</option>
        ))}
      </select>

      {hasActionValue && (
        <>
          <label htmlFor="action-value" className="text-sm text-gray-500">
            Value
          </label>
          <div className="flex flex-col gap-y-2">
            <input
              id="action-value"
              className="border-b-2 text-lg text-black"
              type="text"
              value={actionValue}
              onChange={(e) => {
                setActionValue(e.target.value);
              }}
            />
            <p>{"${title} and ${url} variables are available."}</p>
          </div>
        </>
      )}

      <input
        className="w-32 rounded-full bg-[#1565c0] px-4 py-2 text-base text-white disabled:opacity-70"
        type="button"
        value="Add"
        onClick={() => addHotKey(hotKey, actionType, actionValue)}
        disabled={
          hotKey === "" ||
          hotKey.includes("Unknown") || // case for can't detect key
          actionType === "" ||
          (hasActionValue && actionValue === "")
        }
      />
    </form>
  );
}
